# Generated by Django 5.1.4 on 2025-09-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='Carousel/')),
                ('header_first', models.CharField(max_length=10)),
                ('header_second', models.CharField(max_length=20)),
                ('short_p', models.CharField(max_length=20)),
                ('btn', models.CharField(default='Free Trial', max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='file',
            field=models.FileField(upload_to='uploads/job/'),
        ),
    ]
