# Generated by Django 5.1.4 on 2025-09-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0002_carousel_alter_jobdata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='btn',
            field=models.CharField(default='Free Trial', max_length=16),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='header_first',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='header_second',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='short_p',
            field=models.CharField(max_length=200),
        ),
    ]
