# Generated by Django 5.1.4 on 2025-09-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0003_alter_carousel_btn_alter_carousel_header_first_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('simple_category', models.CharField(max_length=50)),
                ('complex_category', models.CharField(max_length=50)),
                ('super_complex', models.CharField(max_length=50)),
            ],
        ),
    ]
