# Generated by Django 5.1.4 on 2025-09-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0004_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='medium_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
