# Generated by Django 5.1.4 on 2025-09-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0005_pricing_medium_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforAfterImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_img', models.FileField(upload_to='before_after_img/')),
                ('after_img', models.FileField(upload_to='before_after_img/')),
            ],
        ),
    ]
