# Generated by Django 5.2.6 on 2025-10-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0006_beforafterimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
