# Generated by Django 5.1.4 on 2025-10-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0007_delete_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('about_em', models.CharField(max_length=50)),
                ('working_process_h2', models.CharField(max_length=250)),
                ('step_1_p', models.CharField(max_length=250)),
                ('step_2_p', models.CharField(max_length=250)),
                ('pricing_h2', models.CharField(max_length=250)),
                ('basic_plan', models.CharField(max_length=50)),
                ('bli_1', models.CharField(max_length=50)),
                ('bli_2', models.CharField(max_length=50)),
                ('standard_plan', models.CharField(max_length=50)),
                ('premium_plan', models.CharField(max_length=50)),
                ('sli_1', models.CharField(max_length=50)),
                ('sli_2', models.CharField(max_length=50)),
            ],
        ),
    ]
