# Generated by Django 5.1.4 on 2025-10-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0008_servicedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='service_img',
            field=models.FileField(blank=True, null=True, upload_to='service_img/'),
        ),
    ]
