# Generated by Django 5.1.4 on 2025-10-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0009_servicedetail_service_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='pli_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='pli_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='bli_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='bli_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='sli_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='sli_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
