# Generated by Django 5.1.4 on 2025-10-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0010_servicedetail_pli_1_servicedetail_pli_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='img_alt_text',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
