# Generated by Django 5.1.4 on 2025-11-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0011_servicedetail_img_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='beforafterimg',
            name='img_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
