# Generated by Django 5.1.4 on 2025-11-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0012_beforafterimg_img_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='beforafterimg',
            name='after_img_alt_text',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='beforafterimg',
            name='before_img_alt_text',
            field=models.CharField(blank=True, max_length=650, null=True),
        ),
    ]
