# Generated by Django 5.1.4 on 2025-11-03 03:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0013_beforafterimg_after_img_alt_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetailsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('banner', models.FileField(blank=True, null=True, upload_to='blog_banner/')),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
