# Generated by Django 5.1.4 on 2025-11-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0014_blogdetailsview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailsview',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
