# Generated by Django 5.1.4 on 2025-11-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0015_alter_blogdetailsview_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailsview',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
