# Generated by Django 5.1.4 on 2025-11-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0016_alter_blogdetailsview_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailsview',
            name='alt_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
