# Generated by Django 5.1.4 on 2025-11-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0017_blogdetailsview_alt_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='Staff/')),
                ('image_alt_text', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=250)),
                ('fb_link', models.URLField(blank=True, max_length=500, null=True, unique=True)),
                ('twitter_link', models.URLField(blank=True, max_length=500, null=True, unique=True)),
                ('linkedin_link', models.URLField(blank=True, max_length=500, null=True, unique=True)),
                ('instagram_link', models.URLField(blank=True, max_length=500, null=True, unique=True)),
            ],
        ),
    ]
